[package]
name = "json_to_table"
version = "0.1.0"
edition = "2021"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
repository = "https://github.com/zhiburt/tabled"
homepage = "https://github.com/zhiburt/tabled"
documentation = "https://docs.rs/json_to_table"
license = "MIT"
keywords = ["table", "print", "pretty-table", "format", "json"]
categories = ["text-processing", "visualization"]
readme = "README.md"

[features]
color = ["tabled/color"]

[dependencies]
serde_json = "1.*"
tabled = { path = "../" }
